<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StocksSentsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stocks_sents')->delete();
        
        \DB::table('stocks_sents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'stock_id' => 5,
                'quantity_unit_id' => 1,
                'sending_id' => 1,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-18 08:41:33',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            1 => 
            array (
                'id' => 2,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-18 08:41:33',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            2 => 
            array (
                'id' => 3,
                'stock_id' => 7,
                'quantity_unit_id' => 3,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:13:40',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            3 => 
            array (
                'id' => 4,
                'stock_id' => 8,
                'quantity_unit_id' => 1,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:13:40',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            4 => 
            array (
                'id' => 5,
                'stock_id' => 3,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            5 => 
            array (
                'id' => 6,
                'stock_id' => 2,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            6 => 
            array (
                'id' => 7,
                'stock_id' => 9,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            7 => 
            array (
                'id' => 8,
                'stock_id' => 10,
                'quantity_unit_id' => 3,
                'sending_id' => 2,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            8 => 
            array (
                'id' => 9,
                'stock_id' => 11,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            9 => 
            array (
                'id' => 10,
                'stock_id' => 8,
                'quantity_unit_id' => 4,
                'sending_id' => 2,
                'quantity_sent' => 24.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            10 => 
            array (
                'id' => 11,
                'stock_id' => 12,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            11 => 
            array (
                'id' => 12,
                'stock_id' => 13,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 6.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            12 => 
            array (
                'id' => 13,
                'stock_id' => 14,
                'quantity_unit_id' => 5,
                'sending_id' => 2,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            13 => 
            array (
                'id' => 14,
                'stock_id' => 15,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            14 => 
            array (
                'id' => 15,
                'stock_id' => 16,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            15 => 
            array (
                'id' => 16,
                'stock_id' => 17,
                'quantity_unit_id' => 7,
                'sending_id' => 2,
                'quantity_sent' => 24.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            16 => 
            array (
                'id' => 17,
                'stock_id' => 18,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            17 => 
            array (
                'id' => 18,
                'stock_id' => 7,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            18 => 
            array (
                'id' => 19,
                'stock_id' => 19,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            19 => 
            array (
                'id' => 20,
                'stock_id' => 20,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            20 => 
            array (
                'id' => 21,
                'stock_id' => 21,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 8.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            21 => 
            array (
                'id' => 22,
                'stock_id' => 22,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            22 => 
            array (
                'id' => 23,
                'stock_id' => 23,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            23 => 
            array (
                'id' => 24,
                'stock_id' => 24,
                'quantity_unit_id' => 1,
                'sending_id' => 3,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:26:57',
                'updated_at' => '2022-03-19 11:50:17',
            ),
            24 => 
            array (
                'id' => 25,
                'stock_id' => 24,
                'quantity_unit_id' => 3,
                'sending_id' => 3,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:26:57',
                'updated_at' => '2022-03-19 11:50:17',
            ),
            25 => 
            array (
                'id' => 26,
                'stock_id' => 25,
                'quantity_unit_id' => 4,
                'sending_id' => 1,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:47:41',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            26 => 
            array (
                'id' => 27,
                'stock_id' => 8,
                'quantity_unit_id' => 4,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:47:41',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            27 => 
            array (
                'id' => 28,
                'stock_id' => 2,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            28 => 
            array (
                'id' => 29,
                'stock_id' => 26,
                'quantity_unit_id' => 9,
                'sending_id' => 4,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            29 => 
            array (
                'id' => 30,
                'stock_id' => 27,
                'quantity_unit_id' => 1,
                'sending_id' => 4,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            30 => 
            array (
                'id' => 31,
                'stock_id' => 28,
                'quantity_unit_id' => 1,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            31 => 
            array (
                'id' => 32,
                'stock_id' => 29,
                'quantity_unit_id' => 8,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            32 => 
            array (
                'id' => 33,
                'stock_id' => 30,
                'quantity_unit_id' => 8,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            33 => 
            array (
                'id' => 34,
                'stock_id' => 9,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:43:29',
                'updated_at' => '2022-03-19 09:43:29',
            ),
            34 => 
            array (
                'id' => 35,
                'stock_id' => 31,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:43:29',
                'updated_at' => '2022-03-19 09:43:29',
            ),
            35 => 
            array (
                'id' => 36,
                'stock_id' => 33,
                'quantity_unit_id' => 4,
                'sending_id' => 5,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:48:31',
                'updated_at' => '2022-03-19 09:48:31',
            ),
            36 => 
            array (
                'id' => 37,
                'stock_id' => 34,
                'quantity_unit_id' => 8,
                'sending_id' => 6,
                'quantity_sent' => 6.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:50:25',
                'updated_at' => '2022-03-19 13:34:47',
            ),
            37 => 
            array (
                'id' => 38,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:51:49',
                'updated_at' => '2022-03-19 09:51:49',
            ),
            38 => 
            array (
                'id' => 39,
                'stock_id' => 35,
                'quantity_unit_id' => 1,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:54:19',
                'updated_at' => '2022-03-19 09:54:19',
            ),
            39 => 
            array (
                'id' => 40,
                'stock_id' => 7,
                'quantity_unit_id' => 6,
                'sending_id' => 7,
                'quantity_sent' => 8.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            40 => 
            array (
                'id' => 41,
                'stock_id' => 19,
                'quantity_unit_id' => 6,
                'sending_id' => 7,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            41 => 
            array (
                'id' => 42,
                'stock_id' => 36,
                'quantity_unit_id' => 8,
                'sending_id' => 7,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            42 => 
            array (
                'id' => 43,
                'stock_id' => 2,
                'quantity_unit_id' => 10,
                'sending_id' => 5,
                'quantity_sent' => 30.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:44',
                'updated_at' => '2022-03-19 09:55:44',
            ),
            43 => 
            array (
                'id' => 44,
                'stock_id' => 37,
                'quantity_unit_id' => 8,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:57:52',
                'updated_at' => '2022-03-19 09:57:52',
            ),
            44 => 
            array (
                'id' => 45,
                'stock_id' => 3,
                'quantity_unit_id' => 2,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:59:07',
                'updated_at' => '2022-03-19 09:59:07',
            ),
            45 => 
            array (
                'id' => 46,
                'stock_id' => 38,
                'quantity_unit_id' => 11,
                'sending_id' => 8,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            46 => 
            array (
                'id' => 47,
                'stock_id' => 39,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            47 => 
            array (
                'id' => 48,
                'stock_id' => 32,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            48 => 
            array (
                'id' => 49,
                'stock_id' => 37,
                'quantity_unit_id' => 12,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            49 => 
            array (
                'id' => 50,
                'stock_id' => 31,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            50 => 
            array (
                'id' => 51,
                'stock_id' => 19,
                'quantity_unit_id' => 3,
                'sending_id' => 8,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            51 => 
            array (
                'id' => 52,
                'stock_id' => 7,
                'quantity_unit_id' => 13,
                'sending_id' => 8,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            52 => 
            array (
                'id' => 53,
                'stock_id' => 13,
                'quantity_unit_id' => 3,
                'sending_id' => 8,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            53 => 
            array (
                'id' => 54,
                'stock_id' => 42,
                'quantity_unit_id' => 8,
                'sending_id' => 9,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 12:16:49',
                'updated_at' => '2022-03-19 12:16:49',
            ),
            54 => 
            array (
                'id' => 55,
                'stock_id' => 41,
                'quantity_unit_id' => 1,
                'sending_id' => 9,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 12:16:49',
                'updated_at' => '2022-03-19 12:16:49',
            ),
            55 => 
            array (
                'id' => 56,
                'stock_id' => 42,
                'quantity_unit_id' => 8,
                'sending_id' => 10,
                'quantity_sent' => 8.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            56 => 
            array (
                'id' => 57,
                'stock_id' => 2,
                'quantity_unit_id' => 14,
                'sending_id' => 10,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            57 => 
            array (
                'id' => 58,
                'stock_id' => 3,
                'quantity_unit_id' => 8,
                'sending_id' => 10,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            58 => 
            array (
                'id' => 59,
                'stock_id' => 35,
                'quantity_unit_id' => 15,
                'sending_id' => 10,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            59 => 
            array (
                'id' => 60,
                'stock_id' => 43,
                'quantity_unit_id' => 15,
                'sending_id' => 10,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            60 => 
            array (
                'id' => 61,
                'stock_id' => 8,
                'quantity_unit_id' => 4,
                'sending_id' => 10,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            61 => 
            array (
                'id' => 62,
                'stock_id' => 44,
                'quantity_unit_id' => 6,
                'sending_id' => 10,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            62 => 
            array (
                'id' => 63,
                'stock_id' => 36,
                'quantity_unit_id' => 6,
                'sending_id' => 10,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            63 => 
            array (
                'id' => 64,
                'stock_id' => 6,
                'quantity_unit_id' => 8,
                'sending_id' => 10,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            64 => 
            array (
                'id' => 65,
                'stock_id' => 45,
                'quantity_unit_id' => 15,
                'sending_id' => 10,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            65 => 
            array (
                'id' => 66,
                'stock_id' => 27,
                'quantity_unit_id' => 4,
                'sending_id' => 10,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 14:40:54',
                'updated_at' => '2022-03-19 14:40:54',
            ),
            66 => 
            array (
                'id' => 67,
                'stock_id' => 46,
                'quantity_unit_id' => 16,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            67 => 
            array (
                'id' => 68,
                'stock_id' => 47,
                'quantity_unit_id' => 2,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            68 => 
            array (
                'id' => 69,
                'stock_id' => 48,
                'quantity_unit_id' => 3,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            69 => 
            array (
                'id' => 70,
                'stock_id' => 46,
                'quantity_unit_id' => 2,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            70 => 
            array (
                'id' => 71,
                'stock_id' => 49,
                'quantity_unit_id' => 3,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            71 => 
            array (
                'id' => 72,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 11,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:32:58',
                'updated_at' => '2022-03-20 07:32:58',
            ),
            72 => 
            array (
                'id' => 73,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:40:03',
                'updated_at' => '2022-03-20 07:40:03',
            ),
            73 => 
            array (
                'id' => 74,
                'stock_id' => 30,
                'quantity_unit_id' => 17,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:41:01',
                'updated_at' => '2022-03-20 07:41:01',
            ),
            74 => 
            array (
                'id' => 75,
                'stock_id' => 50,
                'quantity_unit_id' => 3,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:41:59',
                'updated_at' => '2022-03-20 07:41:59',
            ),
            75 => 
            array (
                'id' => 76,
                'stock_id' => 12,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:42:21',
                'updated_at' => '2022-03-20 07:42:21',
            ),
            76 => 
            array (
                'id' => 77,
                'stock_id' => 35,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            77 => 
            array (
                'id' => 78,
                'stock_id' => 51,
                'quantity_unit_id' => 3,
                'sending_id' => 12,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            78 => 
            array (
                'id' => 79,
                'stock_id' => 52,
                'quantity_unit_id' => 3,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            79 => 
            array (
                'id' => 80,
                'stock_id' => 53,
                'quantity_unit_id' => 18,
                'sending_id' => 12,
                'quantity_sent' => 26.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            80 => 
            array (
                'id' => 81,
                'stock_id' => 54,
                'quantity_unit_id' => 19,
                'sending_id' => 12,
                'quantity_sent' => 60.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            81 => 
            array (
                'id' => 82,
                'stock_id' => 55,
                'quantity_unit_id' => 19,
                'sending_id' => 12,
                'quantity_sent' => 60.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            82 => 
            array (
                'id' => 83,
                'stock_id' => 56,
                'quantity_unit_id' => 19,
                'sending_id' => 12,
                'quantity_sent' => 60.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            83 => 
            array (
                'id' => 84,
                'stock_id' => 8,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            84 => 
            array (
                'id' => 85,
                'stock_id' => 57,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            85 => 
            array (
                'id' => 86,
                'stock_id' => 21,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            86 => 
            array (
                'id' => 87,
                'stock_id' => 58,
                'quantity_unit_id' => 1,
                'sending_id' => 12,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:48:27',
                'updated_at' => '2022-03-20 07:48:27',
            ),
            87 => 
            array (
                'id' => 88,
                'stock_id' => 59,
                'quantity_unit_id' => 8,
                'sending_id' => 12,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:49:04',
                'updated_at' => '2022-03-20 07:49:04',
            ),
            88 => 
            array (
                'id' => 89,
                'stock_id' => 18,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:50:51',
                'updated_at' => '2022-03-20 07:50:51',
            ),
            89 => 
            array (
                'id' => 90,
                'stock_id' => 44,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:50:51',
                'updated_at' => '2022-03-20 07:51:15',
            ),
            90 => 
            array (
                'id' => 91,
                'stock_id' => 60,
                'quantity_unit_id' => 4,
                'sending_id' => 13,
                'quantity_sent' => 9.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:52:24',
                'updated_at' => '2022-03-20 07:52:24',
            ),
            91 => 
            array (
                'id' => 92,
                'stock_id' => 12,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:52:24',
                'updated_at' => '2022-03-20 07:52:24',
            ),
            92 => 
            array (
                'id' => 93,
                'stock_id' => 43,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:52:24',
                'updated_at' => '2022-03-20 07:52:24',
            ),
            93 => 
            array (
                'id' => 94,
                'stock_id' => 3,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:53:21',
                'updated_at' => '2022-03-20 07:53:21',
            ),
            94 => 
            array (
                'id' => 95,
                'stock_id' => 61,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:53:21',
                'updated_at' => '2022-03-20 07:53:21',
            ),
            95 => 
            array (
                'id' => 96,
                'stock_id' => 14,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 11.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:53:21',
                'updated_at' => '2022-03-20 07:53:21',
            ),
            96 => 
            array (
                'id' => 97,
                'stock_id' => 3,
                'quantity_unit_id' => 2,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:53:52',
                'updated_at' => '2022-03-20 07:53:52',
            ),
            97 => 
            array (
                'id' => 98,
                'stock_id' => 35,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:54:28',
                'updated_at' => '2022-03-20 07:54:28',
            ),
            98 => 
            array (
                'id' => 99,
                'stock_id' => 57,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:56:58',
                'updated_at' => '2022-03-20 07:56:58',
            ),
            99 => 
            array (
                'id' => 100,
                'stock_id' => 62,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:56:58',
                'updated_at' => '2022-03-20 07:56:58',
            ),
            100 => 
            array (
                'id' => 101,
                'stock_id' => 63,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:56:58',
                'updated_at' => '2022-03-20 07:56:58',
            ),
            101 => 
            array (
                'id' => 102,
                'stock_id' => 13,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:56:58',
                'updated_at' => '2022-03-20 07:56:58',
            ),
            102 => 
            array (
                'id' => 103,
                'stock_id' => 37,
                'quantity_unit_id' => 4,
                'sending_id' => 13,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:56:58',
                'updated_at' => '2022-03-20 07:56:58',
            ),
            103 => 
            array (
                'id' => 104,
                'stock_id' => 6,
                'quantity_unit_id' => 8,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:59:47',
                'updated_at' => '2022-03-20 07:59:47',
            ),
            104 => 
            array (
                'id' => 105,
                'stock_id' => 36,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:59:47',
                'updated_at' => '2022-03-20 07:59:47',
            ),
            105 => 
            array (
                'id' => 106,
                'stock_id' => 64,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 07:59:47',
                'updated_at' => '2022-03-20 07:59:47',
            ),
            106 => 
            array (
                'id' => 107,
                'stock_id' => 19,
                'quantity_unit_id' => 3,
                'sending_id' => 13,
                'quantity_sent' => 5.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:01:25',
                'updated_at' => '2022-03-20 08:01:25',
            ),
            107 => 
            array (
                'id' => 108,
                'stock_id' => 65,
                'quantity_unit_id' => 4,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:01:25',
                'updated_at' => '2022-03-20 08:01:25',
            ),
            108 => 
            array (
                'id' => 109,
                'stock_id' => 7,
                'quantity_unit_id' => 20,
                'sending_id' => 13,
                'quantity_sent' => 5.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:01:25',
                'updated_at' => '2022-03-20 08:01:25',
            ),
            109 => 
            array (
                'id' => 110,
                'stock_id' => 37,
                'quantity_unit_id' => 5,
                'sending_id' => 13,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:01:25',
                'updated_at' => '2022-03-20 08:01:25',
            ),
            110 => 
            array (
                'id' => 111,
                'stock_id' => 66,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 6.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:02:31',
                'updated_at' => '2022-03-20 08:02:31',
            ),
            111 => 
            array (
                'id' => 114,
                'stock_id' => 68,
                'quantity_unit_id' => 22,
                'sending_id' => 14,
                'quantity_sent' => 5.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:10:18',
                'updated_at' => '2022-03-20 08:10:18',
            ),
            112 => 
            array (
                'id' => 115,
                'stock_id' => 16,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-20 08:15:52',
                'updated_at' => '2022-03-20 08:15:52',
            ),
            113 => 
            array (
                'id' => 116,
                'stock_id' => 17,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-20 08:15:52',
                'updated_at' => '2022-03-20 08:15:52',
            ),
            114 => 
            array (
                'id' => 117,
                'stock_id' => 69,
                'quantity_unit_id' => 6,
                'sending_id' => 13,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-20 08:15:52',
                'updated_at' => '2022-03-20 08:15:52',
            ),
            115 => 
            array (
                'id' => 118,
                'stock_id' => 15,
                'quantity_unit_id' => 1,
                'sending_id' => 13,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-20 08:15:52',
                'updated_at' => '2022-03-20 08:15:52',
            ),
            116 => 
            array (
                'id' => 121,
                'stock_id' => 72,
                'quantity_unit_id' => 21,
                'sending_id' => 15,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:18:01',
                'updated_at' => '2022-03-20 08:18:01',
            ),
            117 => 
            array (
                'id' => 122,
                'stock_id' => 67,
                'quantity_unit_id' => 4,
                'sending_id' => 15,
                'quantity_sent' => 7.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:18:01',
                'updated_at' => '2022-03-20 08:18:01',
            ),
            118 => 
            array (
                'id' => 123,
                'stock_id' => 21,
                'quantity_unit_id' => 24,
                'sending_id' => 15,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:18:01',
                'updated_at' => '2022-03-20 08:18:01',
            ),
            119 => 
            array (
                'id' => 124,
                'stock_id' => 70,
                'quantity_unit_id' => 20,
                'sending_id' => 15,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-20 08:18:01',
                'updated_at' => '2022-03-20 08:18:01',
            ),
            120 => 
            array (
                'id' => 125,
                'stock_id' => 31,
                'quantity_unit_id' => 2,
                'sending_id' => 16,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:59:43',
                'updated_at' => '2022-03-20 09:09:00',
            ),
            121 => 
            array (
                'id' => 126,
                'stock_id' => 39,
                'quantity_unit_id' => 2,
                'sending_id' => 16,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 08:59:43',
                'updated_at' => '2022-03-20 08:59:57',
            ),
            122 => 
            array (
                'id' => 127,
                'stock_id' => 32,
                'quantity_unit_id' => 2,
                'sending_id' => 16,
                'quantity_sent' => 5.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 09:00:12',
                'updated_at' => '2022-03-20 09:07:13',
            ),
            123 => 
            array (
                'id' => 128,
                'stock_id' => 57,
                'quantity_unit_id' => 1,
                'sending_id' => 16,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 09:07:13',
                'updated_at' => '2022-03-20 09:07:13',
            ),
            124 => 
            array (
                'id' => 129,
                'stock_id' => 73,
                'quantity_unit_id' => 3,
                'sending_id' => 16,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 09:07:13',
                'updated_at' => '2022-03-20 09:07:13',
            ),
            125 => 
            array (
                'id' => 130,
                'stock_id' => 46,
                'quantity_unit_id' => 1,
                'sending_id' => 16,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-20 09:07:13',
                'updated_at' => '2022-03-20 09:07:13',
            ),
        ));

        
    }
}