<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StocksSentsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('stocks_sents')->delete();
        
        \DB::table('stocks_sents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'stock_id' => 5,
                'quantity_unit_id' => 1,
                'sending_id' => 1,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-18 08:41:33',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            1 => 
            array (
                'id' => 2,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-18 08:41:33',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            2 => 
            array (
                'id' => 3,
                'stock_id' => 7,
                'quantity_unit_id' => 3,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:13:40',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            3 => 
            array (
                'id' => 4,
                'stock_id' => 8,
                'quantity_unit_id' => 1,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:13:40',
                'updated_at' => '2022-03-19 08:13:40',
            ),
            4 => 
            array (
                'id' => 5,
                'stock_id' => 3,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            5 => 
            array (
                'id' => 6,
                'stock_id' => 2,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            6 => 
            array (
                'id' => 7,
                'stock_id' => 9,
                'quantity_unit_id' => 2,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            7 => 
            array (
                'id' => 8,
                'stock_id' => 10,
                'quantity_unit_id' => 3,
                'sending_id' => 2,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            8 => 
            array (
                'id' => 9,
                'stock_id' => 11,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            9 => 
            array (
                'id' => 10,
                'stock_id' => 8,
                'quantity_unit_id' => 4,
                'sending_id' => 2,
                'quantity_sent' => 24.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            10 => 
            array (
                'id' => 11,
                'stock_id' => 12,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            11 => 
            array (
                'id' => 12,
                'stock_id' => 13,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 6.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:16:14',
                'updated_at' => '2022-03-19 08:16:14',
            ),
            12 => 
            array (
                'id' => 13,
                'stock_id' => 14,
                'quantity_unit_id' => 5,
                'sending_id' => 2,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            13 => 
            array (
                'id' => 14,
                'stock_id' => 15,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            14 => 
            array (
                'id' => 15,
                'stock_id' => 16,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 0.0,
                'quantity_requested' => NULL,
                'deficit_status' => 2,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            15 => 
            array (
                'id' => 16,
                'stock_id' => 17,
                'quantity_unit_id' => 7,
                'sending_id' => 2,
                'quantity_sent' => 24.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            16 => 
            array (
                'id' => 17,
                'stock_id' => 18,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 10.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            17 => 
            array (
                'id' => 18,
                'stock_id' => 7,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            18 => 
            array (
                'id' => 19,
                'stock_id' => 19,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            19 => 
            array (
                'id' => 20,
                'stock_id' => 20,
                'quantity_unit_id' => 1,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:18:51',
                'updated_at' => '2022-03-19 08:18:51',
            ),
            20 => 
            array (
                'id' => 21,
                'stock_id' => 21,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 8.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            21 => 
            array (
                'id' => 22,
                'stock_id' => 22,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            22 => 
            array (
                'id' => 23,
                'stock_id' => 23,
                'quantity_unit_id' => 6,
                'sending_id' => 2,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:20:17',
                'updated_at' => '2022-03-19 08:20:17',
            ),
            23 => 
            array (
                'id' => 24,
                'stock_id' => 24,
                'quantity_unit_id' => 1,
                'sending_id' => 3,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:26:57',
                'updated_at' => '2022-03-19 11:50:17',
            ),
            24 => 
            array (
                'id' => 25,
                'stock_id' => 24,
                'quantity_unit_id' => 3,
                'sending_id' => 3,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:26:57',
                'updated_at' => '2022-03-19 11:50:17',
            ),
            25 => 
            array (
                'id' => 26,
                'stock_id' => 25,
                'quantity_unit_id' => 4,
                'sending_id' => 1,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:47:41',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            26 => 
            array (
                'id' => 27,
                'stock_id' => 8,
                'quantity_unit_id' => 4,
                'sending_id' => 1,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 08:47:41',
                'updated_at' => '2022-03-19 08:47:41',
            ),
            27 => 
            array (
                'id' => 28,
                'stock_id' => 2,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            28 => 
            array (
                'id' => 29,
                'stock_id' => 26,
                'quantity_unit_id' => 9,
                'sending_id' => 4,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            29 => 
            array (
                'id' => 30,
                'stock_id' => 27,
                'quantity_unit_id' => 1,
                'sending_id' => 4,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            30 => 
            array (
                'id' => 31,
                'stock_id' => 28,
                'quantity_unit_id' => 1,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            31 => 
            array (
                'id' => 32,
                'stock_id' => 29,
                'quantity_unit_id' => 8,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            32 => 
            array (
                'id' => 33,
                'stock_id' => 30,
                'quantity_unit_id' => 8,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:39:37',
                'updated_at' => '2022-03-19 09:39:37',
            ),
            33 => 
            array (
                'id' => 34,
                'stock_id' => 9,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:43:29',
                'updated_at' => '2022-03-19 09:43:29',
            ),
            34 => 
            array (
                'id' => 35,
                'stock_id' => 31,
                'quantity_unit_id' => 2,
                'sending_id' => 4,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:43:29',
                'updated_at' => '2022-03-19 09:43:29',
            ),
            35 => 
            array (
                'id' => 36,
                'stock_id' => 33,
                'quantity_unit_id' => 4,
                'sending_id' => 5,
                'quantity_sent' => 12.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:48:31',
                'updated_at' => '2022-03-19 09:48:31',
            ),
            36 => 
            array (
                'id' => 37,
                'stock_id' => 34,
                'quantity_unit_id' => 8,
                'sending_id' => 6,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:50:25',
                'updated_at' => '2022-03-19 09:50:25',
            ),
            37 => 
            array (
                'id' => 38,
                'stock_id' => 6,
                'quantity_unit_id' => 2,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:51:49',
                'updated_at' => '2022-03-19 09:51:49',
            ),
            38 => 
            array (
                'id' => 39,
                'stock_id' => 35,
                'quantity_unit_id' => 1,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:54:19',
                'updated_at' => '2022-03-19 09:54:19',
            ),
            39 => 
            array (
                'id' => 40,
                'stock_id' => 7,
                'quantity_unit_id' => 6,
                'sending_id' => 7,
                'quantity_sent' => 8.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            40 => 
            array (
                'id' => 41,
                'stock_id' => 19,
                'quantity_unit_id' => 6,
                'sending_id' => 7,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            41 => 
            array (
                'id' => 42,
                'stock_id' => 36,
                'quantity_unit_id' => 8,
                'sending_id' => 7,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:18',
                'updated_at' => '2022-03-19 09:55:18',
            ),
            42 => 
            array (
                'id' => 43,
                'stock_id' => 2,
                'quantity_unit_id' => 10,
                'sending_id' => 5,
                'quantity_sent' => 30.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:55:44',
                'updated_at' => '2022-03-19 09:55:44',
            ),
            43 => 
            array (
                'id' => 44,
                'stock_id' => 37,
                'quantity_unit_id' => 8,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:57:52',
                'updated_at' => '2022-03-19 09:57:52',
            ),
            44 => 
            array (
                'id' => 45,
                'stock_id' => 3,
                'quantity_unit_id' => 2,
                'sending_id' => 5,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 09:59:07',
                'updated_at' => '2022-03-19 09:59:07',
            ),
            45 => 
            array (
                'id' => 46,
                'stock_id' => 38,
                'quantity_unit_id' => 11,
                'sending_id' => 8,
                'quantity_sent' => 4.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            46 => 
            array (
                'id' => 47,
                'stock_id' => 39,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            47 => 
            array (
                'id' => 48,
                'stock_id' => 32,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            48 => 
            array (
                'id' => 49,
                'stock_id' => 37,
                'quantity_unit_id' => 12,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            49 => 
            array (
                'id' => 50,
                'stock_id' => 31,
                'quantity_unit_id' => 2,
                'sending_id' => 8,
                'quantity_sent' => 2.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            50 => 
            array (
                'id' => 51,
                'stock_id' => 19,
                'quantity_unit_id' => 3,
                'sending_id' => 8,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            51 => 
            array (
                'id' => 52,
                'stock_id' => 7,
                'quantity_unit_id' => 13,
                'sending_id' => 8,
                'quantity_sent' => 3.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            52 => 
            array (
                'id' => 53,
                'stock_id' => 13,
                'quantity_unit_id' => 3,
                'sending_id' => 8,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 11:36:50',
                'updated_at' => '2022-03-19 11:36:50',
            ),
            53 => 
            array (
                'id' => 54,
                'stock_id' => 42,
                'quantity_unit_id' => 8,
                'sending_id' => 9,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 12:16:49',
                'updated_at' => '2022-03-19 12:16:49',
            ),
            54 => 
            array (
                'id' => 55,
                'stock_id' => 41,
                'quantity_unit_id' => 1,
                'sending_id' => 9,
                'quantity_sent' => 1.0,
                'quantity_requested' => NULL,
                'deficit_status' => 0,
                'created_at' => '2022-03-19 12:16:49',
                'updated_at' => '2022-03-19 12:16:49',
            ),
        ));

        
    }
}