version: '3'
services:

    #postgres
  db:
    image: postgres:alpine
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: "${DB_DATABASE}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
        SERVICE_TAGS: dev
        SERVICE_NAME: postgres
    volumes:
      #  - dbdata:/var/lib/postgresql/data
       - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf

  #PHP
  app:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./nginx/log:/var/log/nginx/

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/log:/var/log/nginx/
      - ./nginx/conf.d/:/etc/nginx/conf.d/

#Volumes
# volumes:
  # dbdata:
    # driver: local
