version: '3'
services:

    #MySQL
  db:
    image: mysql:5.7.22
    container_name: "${DB_HOST}"
    restart: unless-stopped
    tty: true
<<<<<<< HEAD
    command: --default-authentication-plugin=mysql_native_password #ААААААААААААААААААААААА
=======
>>>>>>> 2b00b683ad037aa0551780383d23816dfc301cf8
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
        - dbdata:/var/lib/mysql/
        - ./mysql/my.cnf:/etc/mysql/my.cnf

  #PHP
  app:
    depends_on:
<<<<<<< HEAD
      - db
    links:
      - db
=======
      - "${DB_HOST}"
    links:
      - "${DB_HOST}"
>>>>>>> 2b00b683ad037aa0551780383d23816dfc301cf8
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

#Volumes
volumes:
  dbdata:
    driver: local
